### ISSUE TITLE
Debian9: apt-cache update failed

### ISSUE THREAD

**Issue by simonrdz** [signalfx/ansible-signalfx-agent#3]
# Description/issue

```
    TASK [signalfx.smart_agent : Add Signalfx Agent repository into sources list] ***
    fatal: [debian9]: FAILED! => {"changed": false, "msg": "apt cache update failed"}
    changed: [debian-latest]
    changed: [ubuntu]
```

# Test environment

molecule with docker

here is the playbook

```
---
- name: Setup Signalfx smart agent
  hosts: all
  become: yes

  tasks:
    - name: "Install package requirements"
      package:
        name:
          - gnupg
        state: present
    - include_role:
        name: "signalfx.smart_agent"
      vars:
        sfx_agent_config:
          signalFxAccessToken: testxxxxx
        monitors:
          - type: cpu
          - type: filesystems
          - type: disk-io
          - type: net-io
          - type: load
          - type: memory
          - type: vmem
          - type: host-metadata
          - type: processlist
```

# How to reproduce

Set [molecule](https://molecule.readthedocs.io/en/stable/installation.html) if you want to test it. but You can use a docker container with the debian:9 image.

Run the playbook on debian:9 fresh installation. You can use vvv option on ansible to have more details

# Detailed Error

```
    The full traceback is:
    WARNING: The below traceback may *not* be related to the actual failure.
      File "/tmp/ansible_apt_repository_payload_UnGu3W/ansible_apt_repository_payload.zip/ansible/modules/packaging/os/apt_repository.py", line 548, in main
      File "/usr/lib/python2.7/dist-packages/apt/cache.py", line 483, in update
        raise FetchFailedException(e)
    
    fatal: [debian9]: FAILED! => {
        "changed": false,
        "invocation": {
            "module_args": {
                "codename": null,
                "filename": "signalfx-agent",
                "install_python_apt": true,
                "mode": 644,
                "repo": "deb https://splunk.jfrog.io/splunk/signalfx-agent-deb release main",
                "state": "present",
                "update_cache": true,
                "validate_certs": true
            }
        },
        "msg": "apt cache update failed"
    }
```
